server:
  port: 8080

spring:
  application:
    name: demo-card-issuance
  datasource:
    url: jdbc:h2:mem:cardissuance;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

flowcore:
  workflow:
    scan-packages: io.flowcore.demo.card

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    io.flowcore: DEBUG
    org.springframework.web: INFO
